let books = [
    {
        id: 1, 
        language: "English", 
        book: "Book 1", 
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id lacus imperdiet, lobortis felis vel, consequat lorem. Donec euismod enim felis, sit amet ultricies sem porttitor nec. Mauris nec mauris congue, sodales urna et, aliquet enim. Nam a sapien quis lacus semper accumsan a sit amet ex. Morbi diam dui, convallis non ligula sit amet, commodo maximus massa. Aenean tincidunt leo eu molestie eleifend. In hac habitasse platea dictumst. Ut feugiat odio ut dui varius commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec euismod turpis molestie lectus dignissim, eget sagittis leo vulputate. Vestibulum condimentum orci vel pharetra hendrerit. Aliquam ullamcorper risus et mollis pulvinar. Sed vel magna sit amet dolor gravida pellentesque. Praesent auctor, nisi dapibus tempus maximus, justo orci consequat tellus, vestibulum tristique erat erat euismod libero.
        In faucibus ante sed mauris cursus, a pharetra tellus malesuada. Duis et viverra nisi. In et fermentum purus, in laoreet lacus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam mollis, risus et sagittis maximus, lectus erat rhoncus arcu, quis eleifend augue risus eu metus. Vestibulum ornare semper magna, ac iaculis justo hendrerit id. In hac habitasse platea dictumst. Maecenas enim justo, varius eu tincidunt ut, varius ut nisl. Duis rhoncus metus vitae erat rhoncus scelerisque. Fusce ornare volutpat porttitor. Ut vulputate efficitur dolor posuere pulvinar. Duis non lacus molestie, congue felis in, facilisis risus. Sed interdum dolor eros, at eleifend lacus rhoncus quis.
        Donec id condimentum quam, ac tempus massa. Nunc sagittis mauris et enim pellentesque tempus. Aenean diam erat, posuere nec quam non, pharetra egestas neque. Ut tristique tempus urna. Quisque diam augue, volutpat a lacinia vulputate, condimentum nec sapien. Mauris scelerisque vulputate odio, placerat vehicula velit maximus a. Nam posuere metus magna, quis tristique turpis sollicitudin elementum. Praesent vulputate posuere nibh, ac interdum turpis hendrerit id. Maecenas sollicitudin nisl quis felis laoreet, varius aliquet sapien varius. Nam fringilla fermentum sapien. Etiam ultrices justo a ultrices efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus imperdiet nisi ultricies risus pulvinar, fringilla eleifend nibh lacinia. Sed sagittis sodales ligula nec tristique. Morbi vel ultricies justo. Fusce pretium mollis velit, quis accumsan tellus mollis quis.
        Proin vehicula dapibus leo, id scelerisque felis ornare sit amet. Aenean placerat vel orci et viverra. Etiam id bibendum est, et eleifend neque. Aliquam consectetur tincidunt arcu eget ultrices. Praesent elit leo, malesuada a nibh condimentum, pulvinar bibendum quam. Vestibulum tincidunt lectus ut pulvinar varius. Mauris sagittis et tellus id bibendum. In pulvinar vel dui nec posuere. Phasellus massa arcu, condimentum vel elementum a, tempor eget metus. Aenean blandit quam lorem, ac sagittis purus posuere gravida.
        Fusce vulputate viverra quam ac fringilla. Integer scelerisque nec quam eu cursus. Suspendisse sed placerat nisi. Nulla molestie feugiat orci ac pretium. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam quis lacus vel purus posuere tempus eu eu eros. In lacus nulla, ultricies sit amet nisi quis, malesuada volutpat orci. Vestibulum vitae sem et odio vehicula euismod. Praesent pellentesque, libero quis placerat mattis, nunc arcu efficitur lacus, sed mattis diam est accumsan neque. In arcu magna, aliquet in varius et, hendrerit quis turpis. Sed eleifend mauris mi, quis dictum enim tempor nec. Duis vitae aliquam lectus. Integer at pretium est, quis sollicitudin odio. Morbi et neque venenatis, bibendum mi ullamcorper, hendrerit magna. Sed tincidunt nisi vel sagittis viverra. Donec magna orci, venenatis vel ante ut, mollis pellentesque risus.`
    },  {
        id: 2, 
        language: "Norwegian", 
        book: "Bok 1", 
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ut auctor massa, sed lobortis leo. Quisque molestie tortor eros, et accumsan mi facilisis nec. Nunc tempor quis lacus eget egestas. Nunc in turpis consequat, dapibus ipsum eget, blandit augue. Nam quis odio id metus auctor luctus. Phasellus eget pretium magna. Sed nulla turpis, aliquam vitae eleifend vel, hendrerit vitae elit. Quisque enim felis, gravida at pulvinar eget, maximus at ante.
        Morbi sit amet varius leo. Pellentesque nunc urna, fringilla eget dapibus quis, dignissim eu purus. In pellentesque nisi ac urna convallis posuere. Proin non nibh varius, fringilla metus quis, vestibulum augue. Nulla facilisi. Maecenas at viverra augue. Quisque vulputate ante massa, sed pulvinar odio sollicitudin non. Vestibulum quis felis mi. Nam lobortis dui ac lorem rutrum maximus. Nulla viverra sollicitudin orci, id suscipit turpis consequat eu. Integer ultricies lacus eu mauris elementum, ut tincidunt turpis auctor.
        Etiam maximus vehicula erat dapibus pellentesque. Duis sem velit, facilisis in quam sed, venenatis congue tellus. Sed tincidunt dui ante, sed molestie urna lobortis in. Etiam auctor in purus vitae aliquet. Nulla turpis enim, ullamcorper ut est id, auctor lacinia mi. Quisque ac diam tempor, posuere diam eget, egestas nisi. Donec sed mauris massa. Proin porta porttitor leo vitae dapibus. Vestibulum id quam non ex viverra posuere. Donec lacinia, nisl porta porta rutrum, nisi magna suscipit magna, non accumsan lacus ipsum vel nisi. Donec eu vulputate felis. Nulla facilisi. Phasellus imperdiet, sem ullamcorper iaculis facilisis, risus dui pretium felis, eget iaculis velit tortor vitae est. Phasellus dapibus nisl mauris, vel maximus tortor vulputate ut.
        Sed finibus pretium malesuada. Nulla ultrices non nulla posuere efficitur. Maecenas pretium felis et nibh mollis, ut suscipit massa dictum. Aliquam congue placerat convallis. Sed ullamcorper enim est, pellentesque vulputate nisi viverra in. Donec consectetur placerat neque, eget malesuada augue congue ultricies. Phasellus eu velit facilisis, elementum augue maximus, bibendum odio. Nulla turpis enim, malesuada nec tellus sit amet, pretium hendrerit quam. Nam vitae varius nisi.
        Duis consectetur felis ut velit imperdiet, vel egestas tellus finibus. Cras mattis, metus et malesuada eleifend, magna risus tempor nunc, non euismod ipsum orci vel massa. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam non condimentum neque, ac condimentum mauris. Integer fermentum eget nunc eget luctus. Donec id magna eu sapien faucibus convallis nec ac augue. Maecenas rhoncus eros in ligula tincidunt iaculis. Proin ultrices ullamcorper elit, eget ultrices leo tristique ut.`
    },  {
        id: 3, 
        language: "Georgian", 
        book: "წიგნი 1", 
        content: `Lorem Ipsum საბეჭდი და ტიპოგრაფიული ინდუსტრიის უშინაარსო ტექსტია. იგი სტანდარტად 1500-იანი წლებიდან იქცა, როდესაც უცნობმა მბეჭდავმა ამწყობ დაზგაზე წიგნის საცდელი ეგზემპლარი დაბეჭდა. მისი ტექსტი არამარტო 5 საუკუნის მანძილზე შემორჩა, არამედ მან დღემდე, ელექტრონული ტიპოგრაფიის დრომდეც უცვლელად მოაღწია. განსაკუთრებული პოპულარობა მას 1960-იან წლებში გამოსულმა Letraset-ის ცნობილმა ტრაფარეტებმა მოუტანა, უფრო მოგვიანებით კი — Aldus PageMaker-ის ტიპის საგამომცემლო პროგრამებმა, რომლებშიც Lorem Ipsum-ის სხვადასხვა ვერსიები იყო ჩაშენებული. 
        გავრცელებული მოსაზრებით, Lorem Ipsum შემთხვევითი ტექსტი სულაც არაა. მისი ფესვები ჯერკიდევ ჩვ. წ. აღ-მდე 45 წლის დროინდელი კლასიკური ლათინური ლიტერატურიდან მოდის. ვირჯინიის შტატში მდებარე ჰემპდენ-სიდნეის კოლეჯის პროფესორმა რიჩარდ მაკკლინტოკმა აიღო ერთ-ერთი ყველაზე იშვიათი ლათინური სიტყვა "consectetur" Lorem Ipsum-პასაჟიდან და გადაწყვიტა მოეძებნა იგი კლასიკურ ლიტერატურაში. ძიება შედეგიანი აღმოჩნდა — ტექსტი Lorem Ipsum გადმოწერილი ყოფილა ციცერონის "de Finibus Bonorum et Malorum"-ის 1.10.32 და 1.10.33 თავებიდან. ეს წიგნი ეთიკის თეორიის ტრაქტატია, რომელიც რენესანსის პერიოდში ძალიან იყო გავრცელებული. Lorem Ipsum-ის პირველი ხაზი, "Lorem ipsum dolor sit amet..." სწორედ ამ წიგნის 1.10.32 თავიდანაა.
        ცნობილი ფაქტია, რომ გვერდის წაკითხვად შიგთავსს შეუძლია მკითხველის ყურადღება მიიზიდოს და დიზაინის აღქმაში ხელი შეუშალოს. Lorem Ipsum-ის გამოყენებით ვღებულობთ იმაზე მეტ-ნაკლებად სწორი გადანაწილების ტექსტს, ვიდრე ერთიდაიგივე გამეორებადი სიტყვებია ხოლმე. შედეგად, ტექსტი ჩვეულებრივ ინგლისურს გავს, მისი წაითხვა კი შეუძლებელია. დღეს უამრავი პერსონალური საგამომცემლო პროგრამა და ვებგვერდი იყენებს Lorem Ipsum-ს, როგორც დროებით ტექსტს წყობის შესავსებად; Lorem Ipsum-ის მოძებნისას კი საძიებო სისტემები ბევრ დაუსრულებელ გვერდს გვიჩვენებენ. წლების მანძილზე ამ ტექსტის უამრავი ვერსია გამოჩნდა, ზოგი შემთხვევით დაშვებული შეცდომის გამო, ზოგი კი — განზრახ, ხუმრობით.
        დღეს უკვე Lorem Ipsum-პასაჟის უამრავი ვერსია არსებობს. მათი დიდი ნაწილი ხუმრობით არის შეცვლილი, ბევრი კი უბრალოდ სიტყვების შემთხვევითი გენერირებით დაიწერა. ინტერნეტში არსებული გენერატორები, როგორც წესი, წინასწარ განსაზღვრული ტექსტის ნაგლეჯს იმეორებენ ხოლმე, ამიტომ ეს პირველი ნამდვილი გენერატორია. იგი რთული და მართებული სტრუქტურის წინადადებების ასაწყობად 200-მდე ლათინური სიტყვისგან შემდგარ ლექსიკონს იყენებს. შედეგად მიიღება ტექსტი, რომელიც ვიზუალურად მაქსიმალურად ახლოსაა რეალურთან. გენერირებული Lorem Ipsum არასოდეს არ არის გამეორებადი, შემთხვევითი სიტყვების ან ხუმრობების შემცველი.
        მათთვის, ვისაც აინტერესებს, ქვევით მოყვანილია Lorem Ipsum-ის ორიგინალი ნაწყვეტი 1500-იანი წლებიდან. ასევე შეგიძლიათ ნახოთ 1.10.32 და 1.10.33 თავები ციცერონის "de Finibus Bonorum et Malorum"-დან, რომელსაც თან ერთვის 1914 წელს ჰ. რექჰამის შესრულებული ინგლისურენოვანი თარგმანი.`
    },  
]

export default books;